apiVersion: v1
kind: PersistentVolume
metadata:
  name: nvme-db
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /mnt/nvme/k8/pp/db #change to your nfs location
    server: 10.219.3.137 #change to your nfs server
