apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: nvme-app-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-originals-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: nvme-app-originals
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-originals-pvc-nc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: nvme-app-originals-nc
